import Foundation

/// Helpers for picking / probing TCP ports.
public enum PortUtility {
    /// Asks the kernel for a free loopback port (used for local databases).
    public static func freePort() -> Int {
        let socketFD = socket(AF_INET, SOCK_STREAM, 0)
        guard socketFD >= 0 else { return Int.random(in: 8100...8999) }
        defer { close(socketFD) }

        var address = sockaddr_in()
        address.sin_family = sa_family_t(AF_INET)
        address.sin_port = 0
        address.sin_addr.s_addr = inet_addr("127.0.0.1")

        let bindResult = withUnsafePointer(to: &address) { pointer -> Int32 in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockaddrPointer in
                Foundation.bind(socketFD, sockaddrPointer, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        guard bindResult == 0 else { return Int.random(in: 8100...8999) }

        var bound = sockaddr_in()
        var length = socklen_t(MemoryLayout<sockaddr_in>.size)
        let nameResult = withUnsafeMutablePointer(to: &bound) { pointer -> Int32 in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockaddrPointer in
                getsockname(socketFD, sockaddrPointer, &length)
            }
        }
        guard nameResult == 0 else { return Int.random(in: 8100...8999) }
        return Int(UInt16(bigEndian: bound.sin_port))
    }

    /// Whether we could bind this address ourselves right now.
    ///
    /// Asked before launching a server, because `/healthcheck` cannot tell us
    /// *whose* server answered: with the port already taken, our own process
    /// dies with `AddrInUse` while the port keeps replying — and the app would
    /// happily report a running server that is somebody else's database.
    public static func isAvailable(host: String, port: Int) -> Bool {
        let socketFD = socket(AF_INET, SOCK_STREAM, 0)
        guard socketFD >= 0 else { return true }
        defer { close(socketFD) }

        var address = sockaddr_in()
        address.sin_family = sa_family_t(AF_INET)
        address.sin_port = UInt16(port).bigEndian
        // Deliberately no SO_REUSEADDR: the conflict is what we are testing for.
        address.sin_addr.s_addr = host == "0.0.0.0" ? INADDR_ANY : inet_addr(host)

        let result = withUnsafePointer(to: &address) { pointer -> Int32 in
            pointer.withMemoryRebound(to: sockaddr.self, capacity: 1) { sockaddrPointer in
                Foundation.bind(socketFD, sockaddrPointer, socklen_t(MemoryLayout<sockaddr_in>.size))
            }
        }
        return result == 0
    }
}

/// What a server should be launched with. Everything except host/port/path is
/// written into a YAML config file, because the CLI takes only three flags.
public struct ServerLaunchConfiguration {
    public var label: String
    public var databasePath: URL
    public var host: String
    public var port: Int
    public var allowReset: Bool
    public var tenant: String
    public var database: String
    /// Identifies the owning profile, or `nil` for a local database session.
    public var profileID: UUID?

    public init(
        label: String,
        databasePath: URL,
        host: String = "127.0.0.1",
        port: Int,
        allowReset: Bool = false,
        tenant: String = ChromaEndpoint.defaultTenant,
        database: String = ChromaEndpoint.defaultDatabase,
        profileID: UUID? = nil
    ) {
        self.label = label
        self.databasePath = databasePath
        self.host = host
        self.port = port
        self.allowReset = allowReset
        self.tenant = tenant
        self.database = database
        self.profileID = profileID
    }

    /// `chroma run` accepts a config file as a positional argument (verified on
    /// CLI 1.4.4 — there is no `--config_path` flag;).
    public func yamlConfiguration() -> String {
        """
        # Generated by ChromaDB Manager — do not edit by hand.
        # Profile: \(label)
        port: \(port)
        listen_address: "\(host)"
        persist_path: "\(databasePath.path)"
        allow_reset: \(allowReset)
        """
    }
}

/// A server this app started, remembered across launches so an orphan left by
/// a crash can be found again.
public struct RunningServerRecord: Codable, Identifiable, Hashable {
    public var pid: Int32
    public var port: Int
    public var host: String
    public var path: String
    public var label: String
    public var startedAt: Date
    /// The engine binary this record was started from. Optional because records
    /// written before carry no path; `ServerIdentity` falls back to the
    /// file name for those.
    public var executablePath: String?

    public var id: Int32 { pid }

    public var isAlive: Bool {
        ProcessInspector.isAlive(pid)
    }

    public init(
        pid: Int32,
        port: Int,
        host: String,
        path: String,
        label: String,
        startedAt: Date,
        executablePath: String? = nil
    ) {
        self.pid = pid
        self.port = port
        self.host = host
        self.path = path
        self.label = label
        self.startedAt = startedAt
        self.executablePath = executablePath
    }
}

/// Tracks pids of servers this app started so they can be killed synchronously
/// when the app quits (no actor hops are available at that point).
public final class ManagedProcessRegistry {
    public static let shared = ManagedProcessRegistry()

    private let lock = NSLock()
    /// The identity each pid had when we registered it, so quitting cannot
    /// signal a stranger that inherited the number in the meantime.
    private var registered: [Int32: ProcessIdentity] = [:]

    public func register(_ pid: Int32) {
        guard let identity = ProcessInspector.identity(of: pid) else { return }
        lock.lock(); registered[pid] = identity; lock.unlock()
    }

    public func unregister(_ pid: Int32) {
        lock.lock(); registered.removeValue(forKey: pid); lock.unlock()
    }

    /// Called from `applicationWillTerminate`.
    public func terminateAll() {
        lock.lock()
        let snapshot = registered
        registered.removeAll()
        lock.unlock()

        for (pid, expected) in snapshot {
            guard ProcessInspector.isAlive(pid) else {
                RunningServerStore.forget(pid: pid)
                continue
            }
            guard let current = ProcessInspector.identity(of: pid) else {
                // Alive but unreadable: signalling it would be signalling a
                // stranger, so it is left alone — and left **remembered**, so
                // the next launch looks for it.
                continue
            }
            guard current.executablePath == expected.executablePath,
                  abs(current.startedAt.timeIntervalSince(expected.startedAt)) < 1 else {
                // The pid belongs to someone else now: our server is gone.
                RunningServerStore.forget(pid: pid)
                continue
            }
            // The record is **not** removed after the signal. `applicationWill
            // Terminate` has no time to wait for the process to actually die,
            // and a server that ignored SIGTERM would otherwise become
            // invisible. The next launch sees `.gone` and drops the record then.
            kill(pid, SIGTERM)
        }
    }
}

/// Persists the "server is running" record to Application Support.
public enum RunningServerStore {
    public static var fileURL: URL {
        AppPaths.serversDirectory.appendingPathComponent("running.json")
    }

    public static func save(_ records: [RunningServerRecord]) throws {
        try AppPaths.ensureDirectory(AppPaths.serversDirectory)
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted]
        try encoder.encode(records).write(to: fileURL, options: .atomic)
    }

    public static func load() -> [RunningServerRecord] {
        guard let data = try? Data(contentsOf: fileURL) else { return [] }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return (try? decoder.decode([RunningServerRecord].self, from: data)) ?? []
    }

    public static func clear() throws {
        try? FileManager.default.removeItem(at: fileURL)
    }

    /// Adds one record without dropping the others: a server started now must
    /// not erase the memory of an orphan left by a previous session.
    public static func upsert(_ record: RunningServerRecord) {
        var records = load().filter { $0.pid != record.pid }
        records.append(record)
        try? save(records)
    }

    public static func forget(pid: Int32) {
        let rest = load().filter { $0.pid != pid }
        if rest.isEmpty {
            try? clear()
        } else {
            try? save(rest)
        }
    }
}

/// Owns `chroma run` child processes: starts one with a generated config,
/// waits until it answers `/healthcheck`, streams its output into the log,
/// stops it gracefully and finds orphans from a previous session.
@MainActor
public final class ChromaProcessManager: ObservableObject {
    public enum State: Equatable {
        case stopped
        case starting
        case running(pid: Int32, since: Date)
        /// A stop we asked for: distinguishes the process dying on command from
        /// the process dying on its own, which must be reported as a failure.
        case stopping
        case failed(String)

        public var isRunning: Bool {
            if case .running = self { return true }
            return false
        }

        public var pid: Int32? {
            if case .running(let pid, _) = self { return pid }
            return nil
        }

        public var startedAt: Date? {
            if case .running(_, let since) = self { return since }
            return nil
        }

        public var title: String {
            switch self {
            case .stopped: return String(localized: "Остановлен")
            case .starting: return String(localized: "Запускается…")
            case .running(let pid, _): return String(localized: "Работает (PID \(pid.plainDigits))")
            case .stopping: return String(localized: "Останавливается…")
            case .failed(let message): return String(localized: "Ошибка: \(message)")
            }
        }
    }

    @Published public private(set) var state: State = .stopped
    @Published public private(set) var endpoint: ChromaEndpoint?
    @Published public private(set) var databasePath: String?
    @Published public private(set) var recentOutput: [String] = []
    /// What the server itself printed about telemetry at startup.
    @Published public private(set) var telemetryStatus: String?
    /// Servers left behind by a previous session.
    @Published public private(set) var orphans: [RunningServerRecord] = []
    /// Processes that are alive, look like ours, and could not be confirmed.
    /// Shown rather than dropped: a record thrown away here is a server nobody
    /// will ever find again.
    @Published public private(set) var unverified: [RunningServerRecord] = []
    /// Set when the process dies unexpectedly, cleared on the next start.
    @Published public private(set) var lastFailure: ServerFailure?
    /// Recomputed once a second while the server runs, so the screen can show
    /// uptime without every view polling a clock of its own.
    @Published public private(set) var uptime: TimeInterval?

    /// Called when the process dies without being asked to. The one server
    /// event worth interrupting the user for — a stop they pressed
    /// themselves is not news.
    public var onUnexpectedExit: ((ServerFailure?, Int32) -> Void)?

    private var process: Process?
    private let log: LogHandler
    private let locator: ToolLocator
    public let serverLog: ServerLogStore
    /// Kept so a failure can name the port the panic does not mention.
    private var lastConfiguration: ServerLaunchConfiguration?
    private var uptimeTimer: Timer?

    public init(
        locator: ToolLocator = .shared,
        serverLog: ServerLogStore = ServerLogStore(),
        log: @escaping LogHandler = noopLogHandler
    ) {
        self.locator = locator
        self.serverLog = serverLog
        self.log = log
    }

    public var isRunning: Bool { state.isRunning }

    /// What the last start was asked to run — the address stays visible after
    /// the process dies, which is exactly when the user wants to see it.
    public var lastLaunch: ServerLaunchConfiguration? { lastConfiguration }

    // MARK: - Orphans

    /// Called at launch: a crash leaves the child process alive, and it keeps
    /// holding the database directory.
    /// Keeps only the records whose pid still belongs to the very process the
    /// record describes. A pid that now belongs to something else is
    /// dropped and reported: it is never offered as a server to stop.
    @discardableResult
    public func refreshOrphans() -> [RunningServerRecord] {
        var kept: [RunningServerRecord] = []
        var confirmed: [RunningServerRecord] = []
        var unconfirmed: [RunningServerRecord] = []
        for record in RunningServerStore.load() {
            let verdict = ServerIdentity.verify(record)
            switch verdict {
            case .confirmed:
                confirmed.append(record)
                kept.append(record)
            case .gone:
                continue
            case .foreign(let reason):
                log(.warning, "Сервер", "Запись о сервере PID \(record.pid.plainDigits) отброшена: \(reason)")
            case .unverified(let reason):
                // Kept, and said out loud. Dropping it was how servers used to
                // go missing.
                unconfirmed.append(record)
                kept.append(record)
                log(.warning, "Сервер",
                    "Процесс PID \(record.pid.plainDigits) не удалось опознать (\(reason)) — запись сохранена, процесс не тронут")
            }
        }
        orphans = confirmed.filter { $0.pid != state.pid }
        unverified = unconfirmed.filter { $0.pid != state.pid }
        if !orphans.isEmpty {
            log(.warning, "Сервер", "Найден сервер от предыдущей сессии: PID \(orphans.map { $0.pid.plainDigits }.joined(separator: ", "))")
        }
        try? RunningServerStore.save(kept)
        return orphans
    }

    /// Verified again immediately before the signal, not just when the list was
    /// built: minutes may have passed, and a pid is not a name.
    public func stopOrphan(_ record: RunningServerRecord) async {
        let verdict = ServerIdentity.verify(record)
        guard verdict.isConfirmed else {
            switch verdict {
            case .gone:
                log(.info, "Сервер", "Процесса PID \(record.pid.plainDigits) уже нет — запись удалена")
            case .foreign(let reason):
                log(.warning, "Сервер", "PID \(record.pid.plainDigits) не остановлен: \(reason)")
            case .unverified(let reason):
                log(.warning, "Сервер",
                    "PID \(record.pid.plainDigits) не остановлен: \(reason). Процесс жив — запись сохранена, попробуйте ещё раз")
            case .confirmed:
                break
            }
            orphans.removeAll { $0.pid == record.pid }
            // Only a record whose fate is known may be dropped.
            if verdict.allowsForgetting {
                RunningServerStore.forget(pid: record.pid)
            } else {
                unverified = unverified.filter { $0.pid != record.pid } + [record]
            }
            return
        }

        // The HTTP API names neither the database nor the server, so this
        // probe cannot confirm identity — the port⇄pid link above already did.
        // It only distinguishes "still serving" from "hung" in the log.
        let probe = ChromaClient(endpoint: ChromaEndpoint(host: record.host, port: record.port), log: { _, _, _ in })
        let answers = (try? await probe.healthcheck()) != nil
        log(.info, "Сервер", answers
            ? "PID \(record.pid.plainDigits) отвечает на \(record.host):\(record.port.plainDigits) — останавливаем"
            : "PID \(record.pid.plainDigits) не отвечает на \(record.host):\(record.port.plainDigits) — останавливаем зависший процесс")

        kill(record.pid, SIGTERM)
        log(.info, "Сервер", "Осиротевшему процессу PID \(record.pid.plainDigits) отправлен SIGTERM")
        orphans.removeAll { $0.pid == record.pid }
        // Kept until something confirms the process is actually gone: a server
        // that ignored the signal must not become invisible.
        if !ProcessInspector.isAlive(record.pid) {
            RunningServerStore.forget(pid: record.pid)
        }
    }

    /// Reuses an orphan instead of killing it: the port already serves the same
    /// database, so the app can simply connect. `nil` when the pid can no longer
    /// be confirmed — the caller starts a fresh server instead.
    public func adoptOrphan(_ record: RunningServerRecord) -> ChromaEndpoint? {
        let verdict = ServerIdentity.verify(record)
        guard verdict.isConfirmed else {
            if let reason = verdict.reason {
                log(.warning, "Сервер", "PID \(record.pid.plainDigits) не принят: \(reason)")
            }
            orphans.removeAll { $0.pid == record.pid }
            if verdict.allowsForgetting {
                RunningServerStore.forget(pid: record.pid)
            } else {
                unverified = unverified.filter { $0.pid != record.pid } + [record]
            }
            return nil
        }
        state = .running(pid: record.pid, since: record.startedAt)
        databasePath = record.path
        let adopted = ChromaEndpoint(host: record.host, port: record.port)
        endpoint = adopted
        orphans.removeAll { $0.pid == record.pid }
        ManagedProcessRegistry.shared.register(record.pid)
        log(.info, "Сервер", "Подключаемся к уже запущенному процессу PID \(record.pid.plainDigits) на \(adopted.baseURLString)")
        return adopted
    }

    // MARK: - Start / stop

    @discardableResult
    public func start(
        _ configuration: ServerLaunchConfiguration,
        readinessTimeout: TimeInterval = 45
    ) async throws -> ChromaEndpoint {
        if isRunning { await stop() }

        // A server this app starts is always loopback-only: ChromaDB
        // has no per-collection rights and no read-only mode, so a database on
        // `0.0.0.0` belongs to whoever reaches the port. Being reachable from
        // the network is the proxy's job, and the proxy checks keys. Checked
        // first, before anything is even looked up: this is a rule about the
        // request, not about the machine.
        guard SecurityAssessment.isLoopback(configuration.host) else {
            let error = ServerError.exposedHost(configuration.host)
            state = .failed(error.errorDescription ?? "")
            log(.error, "Сервер", error.errorDescription ?? "")
            throw error
        }
        // locateAsync, not locate: this method is @MainActor and the lookup may
        // have to ask the login shell.
        guard let cli = await locator.locateAsync("chroma") else {
            throw ServerError.cliMissing
        }
        // Checked before anything is spawned: a server started on a taken port
        // panics and dies, but the port keeps answering, so readiness alone
        // would report success for someone else's server.
        guard PortUtility.isAvailable(host: configuration.host, port: configuration.port) else {
            let failure = ServerFailure.addressInUse(port: configuration.port)
            lastFailure = failure
            state = .failed(failure.message)
            log(.error, "Сервер", failure.message)
            throw ServerError.failed(failure)
        }
        try AppPaths.ensureDirectory(configuration.databasePath)
        try AppPaths.ensureDirectory(AppPaths.serversDirectory)

        let configURL = AppPaths.serversDirectory
            .appendingPathComponent("\(configuration.profileID?.uuidString ?? "local").yaml")
        try configuration.yamlConfiguration().write(to: configURL, atomically: true, encoding: .utf8)

        state = .starting
        recentOutput.removeAll()
        telemetryStatus = nil
        lastFailure = nil
        databasePath = configuration.databasePath.path
        lastConfiguration = configuration
        serverLog.beginRun(
            label: "\(configuration.label) · \(configuration.host):\(configuration.port) · \(configuration.databasePath.path)",
            command: "\(cli) run \(configURL.path)"
        )

        log(.info, "Сервер", "Запуск: \(cli) run \(configURL.path)")
        log(.debug, "Сервер", "Конфигурация: порт \(configuration.port), allow_reset \(configuration.allowReset), путь \(configuration.databasePath.path)")

        let process = Process()
        process.executableURL = URL(fileURLWithPath: cli)
        process.arguments = ["run", configURL.path]
        var environment = ProcessInfo.processInfo.environment
        environment["PATH"] = locator.childProcessPath()
        // Belt and braces: this is the switch the Python server honours.
        environment["ANONYMIZED_TELEMETRY"] = "False"
        process.environment = environment

        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        process.standardInput = FileHandle.nullDevice

        pipe.fileHandleForReading.readabilityHandler = { [weak self] handle in
            let data = handle.availableData
            guard !data.isEmpty, let text = String(data: data, encoding: .utf8) else { return }
            let lines = text.split(separator: "\n").map(String.init)
            Task { @MainActor [weak self] in self?.appendOutput(lines) }
        }

        process.terminationHandler = { [weak self] finished in
            let status = finished.terminationStatus
            Task { @MainActor [weak self] in
                guard let self else { return }
                pipe.fileHandleForReading.readabilityHandler = nil
                ManagedProcessRegistry.shared.unregister(finished.processIdentifier)
                try? RunningServerStore.clear()
                self.process = nil
                self.stopUptimeTimer()
                self.serverLog.endRun(note: "процесс завершился, код \(status)")

                // A crash prints a Rust panic; a stop we asked for exits with 0.
                let failure = ServerFailure.diagnose(
                    output: self.recentOutput,
                    exitCode: status,
                    expectedPort: self.lastConfiguration?.port
                )
                if case .stopping = self.state {
                    // Expected: `stop()` finishes the transition itself.
                } else if case .running = self.state {
                    self.lastFailure = failure
                    self.state = status == 0 ? .stopped : .failed(failure?.message ?? "процесс завершился с кодом \(status)")
                    self.log(status == 0 ? .info : .error, "Сервер", failure?.message ?? "Процесс chroma завершился (код \(status))")
                    self.onUnexpectedExit?(failure, status)
                } else if case .starting = self.state {
                    self.lastFailure = failure
                    self.state = .failed(failure?.message ?? "процесс завершился при запуске (код \(status))")
                    if let failure { self.log(.error, "Сервер", failure.message) }
                }
            }
        }

        do {
            try process.run()
        } catch {
            state = .failed(error.localizedDescription)
            throw ServerError.launchFailed(error.localizedDescription)
        }
        self.process = process
        ManagedProcessRegistry.shared.register(process.processIdentifier)

        let endpoint = ChromaEndpoint(
            host: configuration.host,
            port: configuration.port,
            useTLS: false,
            tenant: configuration.tenant,
            database: configuration.database
        )
        let probe = ChromaClient(endpoint: endpoint, log: { _, _, _ in })

        let deadline = Date().addingTimeInterval(readinessTimeout)
        while Date() < deadline {
            if !process.isRunning { break }
            if (try? await probe.healthcheck()) != nil {
                // Someone could still have taken the port between the check
                // above and our child's own bind; only our live process counts.
                guard process.isRunning else { break }
                let since = Date()
                state = .running(pid: process.processIdentifier, since: since)
                startUptimeTimer(since: since)
                self.endpoint = endpoint
                RunningServerStore.upsert(RunningServerRecord(
                    pid: process.processIdentifier,
                    port: configuration.port,
                    host: configuration.host,
                    path: configuration.databasePath.path,
                    label: configuration.label,
                    startedAt: Date(),
                    executablePath: cli
                ))
                log(.success, "Сервер", "ChromaDB отвечает на \(endpoint.baseURLString)")
                return endpoint
            }
            try? await Task.sleep(nanoseconds: 700_000_000)
        }

        // The process may already be gone — a panic is the usual reason, and it
        // says far more than "did not answer in time".
        let diagnosis = process.isRunning
            ? nil
            : ServerFailure.diagnose(
                output: recentOutput,
                exitCode: process.terminationStatus,
                expectedPort: configuration.port
            )
        let tail = recentOutput.suffix(6).joined(separator: "\n")
        await stop()
        if let diagnosis {
            lastFailure = diagnosis
            state = .failed(diagnosis.message)
            throw ServerError.failed(diagnosis)
        }
        state = .failed("сервер не ответил за \(Int(readinessTimeout)) с")
        throw ServerError.notReady(tail)
    }

    private func startUptimeTimer(since: Date) {
        uptimeTimer?.invalidate()
        uptime = 0
        let timer = Timer(timeInterval: 1, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                guard let self, self.state.isRunning else { return }
                self.uptime = Date().timeIntervalSince(since)
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        uptimeTimer = timer
    }

    private func stopUptimeTimer() {
        uptimeTimer?.invalidate()
        uptimeTimer = nil
        uptime = nil
    }

    /// SIGTERM first (ChromaDB flushes and closes SQLite cleanly), SIGKILL last.
    public func stop(graceful: Bool = true) async {
        guard let process, process.isRunning else {
            // Only our own record goes: other sessions' orphans stay on file.
            if let pid = state.pid { RunningServerStore.forget(pid: pid) }
            state = .stopped
            self.process = nil
            stopUptimeTimer()
            return
        }

        // Marks the exit as expected, so the termination handler does not report
        // our own SIGTERM as a crash.
        state = .stopping
        log(.info, "Сервер", "Остановка сервера (PID \(process.processIdentifier))…")
        if graceful {
            process.terminate()
            for _ in 0..<20 {
                if !process.isRunning { break }
                try? await Task.sleep(nanoseconds: 250_000_000)
            }
        }
        if process.isRunning {
            log(.warning, "Сервер", "Сервер не завершился по SIGTERM — отправляем SIGKILL")
            kill(process.processIdentifier, SIGKILL)
            try? await Task.sleep(nanoseconds: 300_000_000)
        }

        ManagedProcessRegistry.shared.unregister(process.processIdentifier)
        RunningServerStore.forget(pid: process.processIdentifier)
        self.process = nil
        endpoint = nil
        state = .stopped
        stopUptimeTimer()
        serverLog.endRun(note: "остановлен по команде приложения")
        log(.success, "Сервер", "Сервер остановлен")
    }

    private func appendOutput(_ lines: [String]) {
        var written: [String] = []
        for line in lines where !line.trimmingCharacters(in: .whitespaces).isEmpty {
            let clean = line.replacingOccurrences(
                of: "\u{1B}\\[[0-9;]*[a-zA-Z]",
                with: "",
                options: .regularExpression
            )
            written.append(clean)
            // The CLI reports its telemetry state on startup; show it rather
            // than claiming anything ourselves.
            if clean.localizedCaseInsensitiveContains("telemetry") {
                telemetryStatus = clean.trimmingCharacters(in: .whitespaces)
            }
            recentOutput.append(clean)
            if recentOutput.count > 1000 { recentOutput.removeFirst(recentOutput.count - 1000) }
        }
        // The file keeps what the buffer above drops, and survives the run.
        if !written.isEmpty { serverLog.append(written) }
    }

    public enum ServerError: LocalizedError {
        case cliMissing
        case launchFailed(String)
        case notReady(String)
        /// The server said why it died; pass that on instead of a timeout.
        case failed(ServerFailure)
        /// Refused before launch: the app does not put ChromaDB on the network.
        case exposedHost(String)

        public var errorDescription: String? {
            switch self {
            case .exposedHost(let host):
                return String(localized: "Сервер ChromaDB не будет запущен на \(host): приложение запускает его только на 127.0.0.1.")
            case .cliMissing:
                return String(localized: "Chroma CLI не найден. Установите движок на экране «Статус окружения».")
            case .launchFailed(let reason):
                return String(localized: "Не удалось запустить сервер ChromaDB: \(reason)")
            case .notReady(let tail):
                let suffix = tail.isEmpty ? "" : "\n\nПоследний вывод сервера:\n\(tail)"
                return String(localized: "Сервер ChromaDB запустился, но не ответил на /healthcheck.\(suffix)")
            case .failed(let failure):
                return failure.message
            }
        }

        public var recoverySuggestion: String? {
            switch self {
            case .failed(let failure):
                return failure.suggestion
            case .exposedHost:
                return String(localized: "Чтобы к базе подключались с других машин, откройте наружу прокси на экране «Безопасность» — он проверяет ключи и права.")
            default:
                return nil
            }
        }
    }
}
